### ISSUE TITLE
Editorconfig対応分

### ISSUE THREAD

**Issue by g00chy** [NULL-header/fec-frontend#3]
https://github.com/NULL-header/fec-frontend/pull/2#discussion_r490735289
https://github.com/NULL-header/fec-frontend/pull/2#issuecomment-694720762

**Comment by NULL-header** [comment]
対応しておきます。

**Comment by NULL-header** [comment]
@g00chy 
すみません、emptyの件なのですが、今確認したところmasterには存在を確認したのですがdevelopブランチでは確認できませんでした。
実際にありましたらお手数ですが、リンク等でどこを参照しているかご提示願えませんか。

**Comment by g00chy** [comment]
@NULL-header 
申し訳ない。developブランチでtestディレクトリにemptyはありませんでした。
