### ISSUE TITLE
アカウント作成時にパスワードの再確認を要求

### ISSUE THREAD

**Issue by kotarou1192** [NULL-header/fec-frontend#34]
## 概要
大抵のサービスでは、アカウントを作るときには、「再確認にもう一度パスワードを入力してください」のような項目がある。  
それがあると嬉しいなという要望。

## 該当ページ
CreateAccount

## 背景と目的
ユーザーの利便性向上のため。

## 仕様
パスワードの再確認用場所の作成をし、それが既存のパスワードと一致していればOKを出すような仕組みに。

**Comment by NULL-header** [comment]
対応終了。
